### PR TITLE
Focus newly created task

### PR DESCRIPTION
**Pull request by arozans**
This PR tries to close the issue: https://github.com/vit-project/vit/issues/130

### CODE REVIEW

**Comment by thehunmonkgroup** [comment]
The code looks good.

One question: is `focus_added_task` the name we want for the config option? It's best to get this right the first time :) Is there any other name that's more succinct and/or clear?

**Comment by tbabej** [comment]
Perhaps `focus_on_add`?

**Comment by arozans** [comment]
I like @tbabej version too; I think we can also extend config comment with info that task must be visible on active filter to focus on it.

**Comment by thehunmonkgroup** [comment]
Let's go with `focus_on_add`, and also please flesh out the config comment to describe the full behavior of the setting.

**Comment by arozans** [comment]
@thehunmonkgroup can we merge this? :)

**Pull request merged**
