### PR TITLE
Add option to reload the tasks every n minutes

### PR DESCRIPTION
**Pull request by jspricke**
Reimplementation of #162 for 2.x

### CODE REVIEW

**Comment by scottkosty** [comment]
Thanks for porting your patch to VIT 2.x! I still want to understand a couple of things: First, if VIT auto-updated every time one of the Taskwarrior *.data files changed, would this be sufficient or would you still want to set a custom timer? We have some discussion on this at #69, and you brought up a point about that not working if you use taskd to sync but I don't understand why that's the case---if taskd syncs, doesn't that update the *.data files?

**Comment by jspricke** [comment]
file changes: VIT uses URWID for the main loop, where you can add alarms and watches: http://urwid.org/reference/main_loop.html, but the `watch_file()` only takes a `fd`, and I didn't got it to work with the `*.data` files, so I went with the alarm. I think it would make more sense to implement a lazy reload in the tasklib (I did a time based check in my task lib here: https://github.com/jspricke/python-icstask/blob/master/icstask.py#L54).

taskd: If you have an other system pushing changes to taskd, VIT needs to sync those to the local `~/.task` to be able to display them. But I gave up on taskd in the mean time, this is why I didn't add the sync in this implementation.

**Comment by scottkosty** [comment]
@jspricke I see. But suppose (just theoretically) that VIT could detect any change to the *.data files, and whenever a change was detected, VIT refreshes. Would that solve the problem?

**Comment by jspricke** [comment]
> Would that solve the problem?

Yes, implemented this in #191 now. Feel free to merge #191 and close 
this.

**Comment by scottkosty** [comment]
> Yes, implemented this in #191 now.

Cool! Nice work. I have comment, which I'll put over there.

**Comment by thehunmonkgroup** [comment]
Unless there's a use case where a time-based approach has advantages over an event-based approach, which I'm not seeing, #191 should be the way we go.

**Pull request closed without merging**
