### PR TITLE
handle reports w/o columns info. "timesheets" for me doesn't.

### PR DESCRIPTION
**Pull request by dtzWill**
Might only be needed with latest taskwarrior 2.5.2, not sure, and wasn't sure if this was best way to handle it.

If nothing else, heads-up in case you encounter this down the road! :)

Thanks for all your work, BTW! I think the revived vit might be a key player in my return to taskwarrior goodness!

### CODE REVIEW

**Comment by thehunmonkgroup** [comment]
I'm not quite clear how a report can't have any columns, what's the name of the report you're trying to view? Is this a custom report?

**Comment by thehunmonkgroup** [comment]
OK, I got 2.5.2 installed to test this myself. As reported, the ```timesheet``` report has no columns:

```sh
task _show | grep report.timesheet
report.timesheet.filter=(+PENDING and start.after:now-4wks) or (+COMPLETED and end.after:now-4wks)
```
However, I'm unclear if this is a bug in the development version of TaskWarrior, or some new kind of approach to a report that allows zero columns. I can't really fix this issue until I confirm with the TaskWarrior maintainer what's going on there.

**Comment by dtzWill** [comment]
Thank you for investigating! Sorry for not responding sooner, apparently missed your message? :(

I'm also unsure how to best handle this, but FWIW it does appear to be limited to the `timesheet` "report".  Even so, waiting until there's a clearer picture of things sounds like the way to go.  In the meantime perhaps the PR will help lost taskwarrior users ("taskwarriors"? :grin:) encountering this also.  Thanks again.

**Comment by thehunmonkgroup** [comment]
After talking with the TaskWarrior maintainers, I decided to take a different approach to fix this issue.

See the commit message in https://github.com/scottkosty/vit/commit/bf4cb069228e12b26e436b120fb9938a2b6a1531 for a full explanation.

**Comment by dtzWill** [comment]
Perfect, thank you!

**Comment by shaicoleman** [comment]
Can a new version be published to fix this?

**Comment by thehunmonkgroup** [comment]
Doesn't warrant a point release, as the fix addresses features in an unreleased version of TaskWarrior.

You're welcome to run a development version of VIT should you wish to have access to the fix.

**Comment by YAMLcase** [comment]
taskwarrior 2.5.2 has now been released and the bug persists

**Comment by thehunmonkgroup** [comment]
@yamlCase the bug was fixed in https://github.com/vit-project/vit/commit/bf4cb069228e12b26e436b120fb9938a2b6a1531

VIT will probably get a point release in the near future, until then you can run the development version, which is compatible with TaskWarrior 2.5.2: https://github.com/vit-project/vit/blob/2.x/DEVELOPMENT.md

**Comment by YAMLcase** [comment]
Thank you.  I can confirm the 2.X branch has the fix and runs fine under python 3.8 on Ubuntu 20.08.

**Pull request closed without merging**
