### PR TITLE
Support XDG_CONFIG_DIR taskrc location

### PR DESCRIPTION
**Pull request by jspricke**
Taskwarrior 2.6.0 added support for this.

### CODE REVIEW

**Comment by thehunmonkgroup** [comment]
Since you abstracted the xdg functionality (which I like, thanks!), did you test that it's still operating correctly in both places it's now used?

**Comment by jspricke** [comment]
Yes, I tested .vit, ~/.config/vit and .taskrc and ~/.config/task/taskrc.

**Comment by thehunmonkgroup** [comment]
Thanks for your work on this!

**Comment by jspricke** [comment]
Thanks for the quick merge. Do you plan a new release soon?

**Comment by thehunmonkgroup** [comment]
I have no estimate for that.

**Pull request merged**
